"""@order scope catalog package."""

from .constraints import (
    CONSTRAINTS,
    ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU,
    ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT,
    ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE,
    ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE,
    ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE,
    ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS,
    ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED,
    ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE,
    ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20,
)
from .events import EVENTS, ORDER_EVENT_ORDER_CANCELLED, ORDER_EVENT_ORDER_CREATED, ORDER_EVENT_OUT_OF_STOCK
from .glossary import GLOSSARY
from .models import MODELS, ORDER_MODEL_BATCH, ORDER_MODEL_MONEY, ORDER_MODEL_ORDER, ORDER_MODEL_ORDER_LINE
from .properties import (
    ORDER_PROPERTY_ALLOCATION_REQUIRES_MATCHING_SKU,
    ORDER_PROPERTY_BATCH_ALLOCATION_IDEMPOTENT,
    ORDER_PROPERTY_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE,
    ORDER_PROPERTY_MONEY_ADDITION_IS_COMMUTATIVE,
    ORDER_PROPERTY_MONEY_SERIALIZATION_ROUND_TRIP,
    ORDER_PROPERTY_ORDER_LINE_SKU_FORMAT_VALIDATION,
    ORDER_PROPERTY_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE,
    PROPERTIES,
)

__all__ = [
    "CONSTRAINTS",
    "EVENTS",
    "GLOSSARY",
    "MODELS",
    "ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU",
    "ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT",
    "ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE",
    "ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE",
    "ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE",
    "ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS",
    "ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED",
    "ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE",
    "ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20",
    "ORDER_EVENT_ORDER_CANCELLED",
    "ORDER_EVENT_ORDER_CREATED",
    "ORDER_EVENT_OUT_OF_STOCK",
    "ORDER_MODEL_BATCH",
    "ORDER_MODEL_MONEY",
    "ORDER_MODEL_ORDER",
    "ORDER_MODEL_ORDER_LINE",
    "ORDER_PROPERTY_ALLOCATION_REQUIRES_MATCHING_SKU",
    "ORDER_PROPERTY_BATCH_ALLOCATION_IDEMPOTENT",
    "ORDER_PROPERTY_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE",
    "ORDER_PROPERTY_MONEY_ADDITION_IS_COMMUTATIVE",
    "ORDER_PROPERTY_MONEY_SERIALIZATION_ROUND_TRIP",
    "ORDER_PROPERTY_ORDER_LINE_SKU_FORMAT_VALIDATION",
    "ORDER_PROPERTY_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE",
    "PROPERTIES",
]