"""@order scope constraints."""

from src.catalog.types import Constraint


ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE = Constraint(
    id="ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE",
    category="invariant",
    description="Batch의 가용 수량은 절대 음수가 될 수 없다",
)

ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE = Constraint(
    id="ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE",
    category="invariant",
    description="Order는 최소 1개의 OrderLine을 가져야 한다",
)

ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE = Constraint(
    id="ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE",
    category="invariant",
    description="Money의 amount는 0 이상이어야 한다",
)

ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT = Constraint(
    id="ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT",
    category="invariant",
    description="같은 OrderLine을 같은 Batch에 두 번 배정하면 두 번째는 무시된다 (멱등성)",
)

ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED = Constraint(
    id="ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED",
    category="policy",
    description="Order 생성 시 OrderCreated 이벤트가 발행된다",
)

ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU = Constraint(
    id="ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU",
    category="policy",
    description="배정 시 SKU가 일치해야 한다",
)

ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS = Constraint(
    id="ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS",
    category="policy",
    description="주문 취소 시 모든 배정이 해제되어야 한다",
)

ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE = Constraint(
    id="ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE",
    category="format",
    description="Currency는 ISO 4217 3자리 대문자 코드",
)

ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20 = Constraint(
    id="ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20",
    category="format",
    description="SKU는 대문자 영숫자 + 하이픈, 최대 20자",
)

CONSTRAINTS: tuple[Constraint, ...] = (
    ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE,
    ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE,
    ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE,
    ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT,
    ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED,
    ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU,
    ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS,
    ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE,
    ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20,
)

__all__ = [
    "CONSTRAINTS",
    "ORDER_CONSTRAINT_ALLOCATION_REQUIRES_MATCHING_SKU",
    "ORDER_CONSTRAINT_BATCH_ALLOCATION_IDEMPOTENT",
    "ORDER_CONSTRAINT_BATCH_AVAILABLE_QUANTITY_NON_NEGATIVE",
    "ORDER_CONSTRAINT_CURRENCY_IS_ISO_4217_UPPERCASE",
    "ORDER_CONSTRAINT_MONEY_AMOUNT_NON_NEGATIVE",
    "ORDER_CONSTRAINT_ORDER_CANCELLATION_RELEASES_ALLOCATIONS",
    "ORDER_CONSTRAINT_ORDER_CREATION_PUBLISHES_ORDER_CREATED",
    "ORDER_CONSTRAINT_ORDER_REQUIRES_AT_LEAST_ONE_ORDER_LINE",
    "ORDER_CONSTRAINT_SKU_IS_UPPERCASE_ALNUM_HYPHEN_MAX_20",
]